server:
  port: 8081
  servlet:
    context-path: /biddingmarket
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小

spring:
     datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/biddingmarket?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: 123456
     jpa:
       show-sql: true
     mvc:
       view:
         prefix: /
         suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.biddingmarket.entity
   #devtools插件
devtools:
    restart:
      enabled: true #是否支持热部署

#mybatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

  # 打印sql
logging:
    level:
       com.aviation.mapper: DEBUG
